export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID"
export const DELETE_CONTACT_USER_ID = "DELETE_CONTACT_USER_ID"
export const SET_MESSAGE_TYPING_VALUE = "SET_MESSAGE_TYPING_VALUE"
export const SEND_MESSAGE = "SEND_MESSAGE"